### ISSUE TITLE
Where does the .deb come from

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-sumologic-collector#4]
Can this be automated based on ansible facts and `get_url`?  Or if not, it would be handy to have some documentation on where to get it from

**Comment by jszwedko** [comment]
I'll add some documentation, but unfortunately, the deb is only available from Sumologic (after you create an account) and I wasn't comfortable rehosting it.

**Comment by rafecolton** [comment]
:+1: thought that might be the case - documentation worksforme.
